name: strive-build

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'test/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'test/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore
      run: dotnet restore strive.sln 
      
    - name: Build
      run: dotnet build --no-restore strive.sln
      
    - name: Test
      run: dotnet test strive.sln 

